// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoAlans_API.Data;

namespace ProjetoAlans_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210501013137_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoAlans_API.models.Funcionario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("custoDia")
                        .HasColumnType("float");

                    b.Property<string>("escala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Funcionarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            custoDia = 200.0,
                            escala = "5x2",
                            nome = "Marta"
                        },
                        new
                        {
                            id = 2,
                            custoDia = 300.0,
                            escala = "12x36",
                            nome = "Paula"
                        },
                        new
                        {
                            id = 3,
                            custoDia = 500.0,
                            escala = "6x1",
                            nome = "Laura"
                        },
                        new
                        {
                            id = 4,
                            custoDia = 150.0,
                            escala = "5x2",
                            nome = "Luiza"
                        },
                        new
                        {
                            id = 5,
                            custoDia = 50.0,
                            escala = "12x36",
                            nome = "Lucas"
                        },
                        new
                        {
                            id = 6,
                            custoDia = 60.0,
                            escala = "6x1",
                            nome = "Pedro"
                        },
                        new
                        {
                            id = 7,
                            custoDia = 75.0,
                            escala = "12x36",
                            nome = "Paulo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
